name: Run E2E Tests

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn ci
        
       
      - name: Build
        run: yarn build
        
        
      - name: Test
        run: yarn test
        
        
      - name: Lint
        run: yarn lint
        
      
      - name: Ts-prune
        run: yarn ts-prune
      
